[workspace]
members = ["simfony-cli", "simfony-wallet"]
resolver = "2"

[workspace.dependencies]
simfony = { git = "https://github.com/m-kus/simfony", rev = "c90ac06d66fc4d6090f7a8e230805000d817e123", features = ["serde"] }
